"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fields_1 = require("../../icure-form/fields");
const icure_button_group_1 = require("../../icure-button-group");
const icure_date_picker_1 = require("../../icure-date-picker");
const icure_dropdown_field_1 = require("../../icure-dropdown-field");
const icure_form_1 = require("../../icure-form");
const icure_label_1 = require("../../icure-label");
const icure_text_field_1 = require("../../icure-text-field");
const icure_button_1 = require("../../icure-button");
const form_selection_button_1 = require("../../icure-form/renderer/form/form-selection-button");
customElements.define('icure-form-checkbox', fields_1.CheckBox);
customElements.define('icure-form-date-picker', fields_1.DatePicker);
customElements.define('icure-form-date-time-picker', fields_1.DateTimePicker);
customElements.define('icure-form-dropdown-field', fields_1.DropdownField);
customElements.define('icure-button-group', icure_button_group_1.IcureButtonGroup);
customElements.define('icure-date-picker-field', icure_date_picker_1.IcureDatePickerField);
customElements.define('icure-dropdown-field', icure_dropdown_field_1.IcureDropdownField);
customElements.define('icure-form', icure_form_1.IcureForm);
customElements.define('icure-label', icure_label_1.IcureLabel);
customElements.define('icure-button', icure_button_1.IcureButton);
customElements.define('icure-text-field', icure_text_field_1.IcureTextField);
customElements.define('icure-form-items-list-field', fields_1.ItemsListField);
customElements.define('icure-form-label', fields_1.Label);
customElements.define('icure-form-button', fields_1.Button);
customElements.define('icure-form-measure-field', fields_1.MeasureField);
customElements.define('icure-form-number-field', fields_1.NumberField);
customElements.define('icure-form-radio-button', fields_1.RadioButton);
customElements.define('icure-form-text-field', fields_1.TextField);
customElements.define('icure-form-time-picker', fields_1.TimePicker);
customElements.define('icure-form-token-field', fields_1.TokenField);
customElements.define('form-selection-button', form_selection_button_1.FormSelectionButton);
//# sourceMappingURL=index.js.map